<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5Vin0kI\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5Vin0kI/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5Vin0kI.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5Vin0kI\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container5Vin0kI\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '5Vin0kI',
    'container.build_id' => '00c282ce',
    'container.build_time' => 1644879598,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5Vin0kI');
